=== eis-group-opensource/x4j-analytic/src/main/resources/META-INF/reportMetadata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
	jaxb:version="2.0" xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.exigen.com/reportMetadata" xmlns:tns="http://www.exigen.com/reportMetadata"
	elementFormDefault="qualified">

	<annotation>
		<appinfo>
			<jaxb:schemaBindings>
				<jaxb:package name="com.exigen.ipb.operationalreports.model" />
			</jaxb:schemaBindings>
		</appinfo>
	</annotation>


	<simpleType name="parameterType">
		<restriction base="string">
			<enumeration value="STRING" />
			<enumeration value="DATE" />
			<enumeration value="TIME" />
			<enumeration value="DATE_TIME" />
			<enumeration value="TIMESTAMP" />
			<enumeration value="INTEGER" />
			<enumeration value="MONEY" />
			<enumeration value="FLOAT" />
			<enumeration value="BOOLEAN" />
			<enumeration value="LOOKUP" />
			<enumeration value="MULTILOOKUP" />
		</restriction>
	</simpleType>

	<complexType name="Parameter">
		<sequence>
			<element name="description" type="string" minOccurs="1"
				maxOccurs="1" />
			<element name="name" type="string" minOccurs="1" maxOccurs="1" />
			<element name="category" type="string" />
			<element name="type" type="tns:parameterType" minOccurs="1"
				maxOccurs="1" />
			<element name="required" type="boolean" minOccurs="0"
				maxOccurs="1" />
			<element name="default" type="string" minOccurs="0"
				maxOccurs="1" />
			<element name="validator" type="string" minOccurs="0"
				maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="format">
		<sequence>
			<element name="name" type="string" minOccurs="1" maxOccurs="1" />
			<element name="template" type="string" minOccurs="1"
				maxOccurs="1" />
		</sequence>
	</complexType>
	
	<complexType name="templates">
		<sequence>
			<element name="format" type="tns:format" minOccurs="1"
				maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="Query">
		<sequence>
			<element name="name" type="string" minOccurs="1" maxOccurs="1" />
			<element name="dataSource" type="string" minOccurs="0"
				maxOccurs="1" />
			<element name="sql" type="string" minOccurs="1" maxOccurs="1" />
		</sequence>
	</complexType>

	<simpleType name="paramList">
		<list itemType="string" />
	</simpleType>

	<complexType name="Script">
		<sequence>
			<element name="name" type="string" minOccurs="1" maxOccurs="1" />
			<element name="parameters" type="tns:paramList" minOccurs="0"
				maxOccurs="1" />
			<element name="type" type="string" minOccurs="0" maxOccurs="1" />
			<element name="text" type="string" minOccurs="1" maxOccurs="1" />
		</sequence>
	</complexType>


	<complexType name="Attribute">
		<sequence>
			<element name="name" type="string" minOccurs="1" maxOccurs="1" />
			<element name="value" type="string" minOccurs="1" maxOccurs="1" />
		</sequence>
	</complexType>

	<element name="report-metadata">
		<complexType>
			<sequence>
				<element name="parent" type="string" minOccurs="0"
					maxOccurs="1" />
				<element name="id" type="string" minOccurs="1" maxOccurs="1" />
				<element name="name" type="string" minOccurs="1" maxOccurs="1" />
				<element name="category" type="string" minOccurs="0"
					maxOccurs="1" />
				<element name="description" type="string" minOccurs="1"
					maxOccurs="1" />
				<element name="template" type="string" minOccurs="0"
					maxOccurs="1" />
				<element name="formats" type="string" minOccurs="0"
					maxOccurs="1" />
				<element name="delivery" type="string" minOccurs="0"
					maxOccurs="1" />
				<element name="folder" type="string" minOccurs="0"
					maxOccurs="1" />
				<element name="file" type="string" minOccurs="0"
					maxOccurs="1" />
				<element name="templates" type="tns:templates" minOccurs="0"
					maxOccurs="1" />
				<element name="cube" type="string" minOccurs="0" maxOccurs="1" />
				<element name="parameter" type="tns:Parameter" minOccurs="0"
					maxOccurs="unbounded" />
				<element name="query" type="tns:Query" minOccurs="0"
					maxOccurs="unbounded" />
				<element name="script" type="tns:Script" minOccurs="0"
					maxOccurs="unbounded" />
				<element name="attribute" type="tns:Attribute" minOccurs="0"
					maxOccurs="unbounded" />

			</sequence>
		</complexType>
	</element>

</schema>

=== eis-group-opensource/x4j-analytic/src/test/resources/TestData.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:report-metadata xmlns:tns="http://www.exigen.com/reportMetadata"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.example.org/reportMetadata reportMetadata.xsd">
	
	<tns:id>parent.xml</tns:id>
	
	<tns:name>Parent</tns:name>
	
	<tns:category></tns:category>
	
	<tns:description>common queries and parameters</tns:description>
	
	<tns:template></tns:template>
	
	<tns:parameter>
	    <tns:description>LOB</tns:description>
		<tns:name>lob</tns:name>
		<tns:category>General</tns:category>
		<tns:type>MULTILOOKUP</tns:type>
	</tns:parameter>
	
	
	<tns:parameter>
	    <tns:description>Product</tns:description>
		<tns:name>product</tns:name>
		<tns:category>General</tns:category>
		<tns:type>MULTILOOKUP</tns:type>
	</tns:parameter>
	
	<tns:parameter>
	    <tns:description>State</tns:description>
		<tns:name>risk_state</tns:name>
		<tns:category>General</tns:category>
		<tns:type>MULTILOOKUP</tns:type>
	</tns:parameter>
	
	<tns:parameter>
	    <tns:description>Agency</tns:description>
		<tns:name>agency</tns:name>
		<tns:category>General</tns:category>
		<tns:type>MULTILOOKUP</tns:type>
	</tns:parameter>
	
	
	
	<tns:query>
		<tns:name>risk_state</tns:name>
		<tns:sql>
			SELECT
			  RISK_STATE_CODE,
			  DESCRIPTION 
			FROM RISK_STATE
			ORDER BY DESCRIPTION
  		</tns:sql>
	</tns:query>
	
	<tns:query>
		<tns:name>product</tns:name>
		<tns:sql>
			SELECT DISTINCT
			  PRODUCT_CODE,
			  PRODUCT_NAME
			FROM PRODUCT WHERE LOBCD IN (:lob)
  		</tns:sql>
	</tns:query>
	
	<tns:query>
		<tns:name>lob</tns:name>
		<tns:sql>
			SELECT DISTINCT
			  LOBCD,
			  LOB_DESCRIPTION			  
			FROM PRODUCT
  		</tns:sql>
	</tns:query>
	
	<tns:query>
		<tns:name>agency</tns:name>
		<tns:sql>
			SELECT DISTINCT
			  AGENCY_CD,
              AGENCY_NAME
			FROM AGENCY
  		</tns:sql>
	</tns:query>
	
		<tns:query>
		<tns:name>billing_transaction_type</tns:name>
		<tns:sql>
			 SELECT BILLING_TRANSACTION_CODE,
			        DESCRIPTION
			 FROM BILLING_TRANSACTION_TYPE
		</tns:sql>
	</tns:query>
	
	<tns:attribute>
	 <tns:name>PARENT_FILTER</tns:name>
	 <tns:value>(
	            (  RISK_STATE_CODE in  (:risk_state) OR RISK_STATE_CODE IS NULL )
				 AND  PRODUCT_CODE in  (:product) 
				 AND ( AGENCY_CODE  in (:agency) OR AGENCY_CODE IS NULL )
				)</tns:value>
	</tns:attribute>
	
</tns:report-metadata>

=== eis-group-opensource/x4j-analytic/src/test/resources/testTableMacro.xml
<?xml version="1.0" encoding="UTF-8"?>
<report-metadata xmlns="http://www.exigen.com/reportMetadata"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/reportMetadata reportMetadata.xsd">

	<id>testTableMacro.xml</id>
	<name>Test Table Macro</name>
	<category>Data Dictionary>Data Quality</category>	
	<template>testTableMacro.xlsx</template>
	
	
	<query>
		<name>sanityCheckData</name>
		<sql>
		<![CDATA[
			SELECT * FROM SANITY_CHECK
			ORDER BY TIMESTAMP DESC			
		]]>
  		</sql>
	</query>

</report-metadata>
